In [1]:
import pandas as pd
import numpy as np
import pickle
import warnings

In [2]:
df = pd.read_csv("info2.csv")

In [3]:
df['date'].replace('\r\n',' ', regex=True)

0     2022/06/03
1     2022/06/04
2     2022/06/05
3     2022/06/06
4     2022/06/07
5     2022/06/08
6     2022/06/09
7     2022/06/10
8     2022/06/11
9     2022/06/12
10    2022/06/13
11    2022/06/14
12    2022/06/15
13    2022/06/16
14    2022/06/17
15    2022/06/18
16    2022/06/19
17    2022/06/20
18    2022/06/21
19    2022/06/22
20    2022/06/23
21    2022/06/24
22    2022/06/25
23    2022/06/26
24    2022/06/27
25    2022/06/28
26    2022/06/29
27    2022/06/30
28    2022/07/01
Name: date, dtype: object

In [6]:
convertedArr = df[['lon_data','lat_data','temp_data','pressure_data','humidity_data','cloud_data','visibility_data','wind_speed_data']][:30].values.tolist()

In [7]:
convertedArr

[[44.3501, 14.8516, 292.26, 1013.0, 33.0, 2.0, 10000.0, 1.33],
 [44.3501, 14.8516, 291.61, 1014.0, 44.0, 11.0, 10000.0, 1.95],
 [44.3501, 14.8516, 291.84, 1015.0, 37.0, 47.0, 10000.0, 0.74],
 [44.3501, 14.8516, 292.2, 1015.0, 33.0, 99.0, 10000.0, 0.78],
 [44.3501, 14.8516, 292.11, 1014.0, 41.0, 41.0, 10000.0, 0.81],
 [44.3501, 14.8516, 293.53, 1014.0, 23.0, 17.0, 0.0, 0.31],
 [44.3501, 14.8516, 293.03, 1016.0, 18.0, 0.0, 0.0, 3.11],
 [44.3501, 14.8516, 293.62, 1016.0, 17.0, 63.0, 0.0, 2.62],
 [44.3501, 14.8516, 293.87, 1014.0, 12.0, 1.0, 0.0, 1.94],
 [44.3501, 14.8516, 293.9, 1012.0, 13.0, 0.0, 0.0, 1.18],
 [44.3501, 14.8516, 295.51, 1013.0, 25.0, 0.0, 0.0, 0.62],
 [44.3501, 14.8516, 294.07, 1015.0, 35.0, 89.0, 0.0, 0.67],
 [44.3501, 14.8516, 295.3, 1015.0, 20.0, 28.0, 0.0, 0.95],
 [44.3501, 14.8516, 296.1, 1015.0, 19.0, 82.0, 0.0, 0.94],
 [44.3501, 14.8516, 295.17, 1015.0, 16.0, 0.0, 0.0, 1.44],
 [44.3501, 14.8516, 293.29, 1014.0, 16.0, 0.0, 0.0, 2.63],
 [44.3501, 14.8516, 293.25, 1015.0, 29.0, 0.0, 0.0, 0.51],
 [44.3501, 14.8516, 293.41, 1017.0, 35.0, 0.0, 0.0, 0.79],
 [44.3501, 14.8516, 293.32, 1017.0, 21.0, 0.0, 0.0, 2.28],
 [44.3501, 14.8516, 294.95, 1016.0, 20.0, 65.0, 0.0, 3.52],
 [44.3501, 14.8516, 293.5, 1017.0, 46.0, 0.0, 0.0, 0.68],
 [44.3501, 14.8516, 293.12, 1017.0, 62.0, 0.0, 0.0, 0.43],
 [44.3501, 14.8516, 293.24, 1017.0, 62.0, 36.0, 0.0, 0.65],
 [44.3501, 14.8516, 292.98, 1016.0, 59.0, 1.0, 0.0, 0.87],
 [44.3501, 14.8516, 293.04, 1016.0, 61.0, 71.0, 0.0, 0.78],
 [44.3501, 14.8516, 291.29, 1016.0, 77.0, 14.0, 0.0, 1.24],
 [44.3501, 14.8516, 291.89, 1016.0, 71.0, 0.0, 0.0, 1.02],
 [44.3501, 14.8516, 291.78, 1018.0, 65.0, 1.0, 0.0, 1.38],
 [44.3501, 14.8516, 291.51, 1019.0, 71.0, 34.0, 0.0, 1.55]]

In [8]:
warnings.filterwarnings("ignore")
with open("model.pkl",'rb') as f:
    fm = pickle.load(f)
    convertedArr

In [9]:
prediction = fm.predict(convertedArr)
print(prediction)

[-959.7982825  -956.67396191 -950.467438   -940.1408325  -951.24412405
   60.91954563   58.10660804   70.79043235   57.30305626   56.84197061
   58.04973293   77.11566221   63.43181325   74.51064326   57.49001394
   57.70746283   58.09381398   58.86706563   58.10540097   72.08627103
   59.92682804   61.35303431   68.84139377   61.41297993   75.92287358
   65.77352729   62.30329854   62.08234584   69.48867198]

In [10]:
len(prediction)

29

In [11]:
newDF = pd.DataFrame({'Prediction':prediction,'Date':df['date'].replace('\r\n',' ', regex=True)})

In [12]:
newDF

    Prediction         Date
0  -959.798282  2022/06/03
1  -956.673962  2022/06/04
2  -950.467438  2022/06/05
3  -940.140833  2022/06/06
4  -951.244124  2022/06/07
5    60.919546  2022/06/08
6    58.106608  2022/06/09
7    70.790432  2022/06/10
8    57.303056  2022/06/11
9    56.841971  2022/06/12
10   58.049733  2022/06/13
11   77.115662  2022/06/14
12   63.431813  2022/06/15
13   74.510643  2022/06/16
14   57.490014  2022/06/17
15   57.707463  2022/06/18
16   58.093814  2022/06/19
17   58.867066  2022/06/20
18   58.105401  2022/06/21
19   72.086271  2022/06/22
20   59.926828  2022/06/23
21   61.353034  2022/06/24
22   68.841394  2022/06/25
23   61.412980  2022/06/26
24   75.922874  2022/06/27
25   65.773527  2022/06/28
26   62.303299  2022/06/29
27   62.082346  2022/06/30
28   69.488672  2022/07/01

In [13]:
newDF['Date']

0     2022/06/03
1     2022/06/04
2     2022/06/05
3     2022/06/06
4     2022/06/07
5     2022/06/08
6     2022/06/09
7     2022/06/10
8     2022/06/11
9     2022/06/12
10    2022/06/13
11    2022/06/14
12    2022/06/15
13    2022/06/16
14    2022/06/17
15    2022/06/18
16    2022/06/19
17    2022/06/20
18    2022/06/21
19    2022/06/22
20    2022/06/23
21    2022/06/24
22    2022/06/25
23    2022/06/26
24    2022/06/27
25    2022/06/28
26    2022/06/29
27    2022/06/30
28    2022/07/01
Name: Date, dtype: object

In [13]:
newDF.to_csv('predictedData.csv', index=False)